//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilichevKurs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentTypes
    {
        public EquipmentTypes()
        {
            this.MilitaryEquipment = new HashSet<MilitaryEquipment>();
        }
    
        public int TypeID { get; set; }
        public string TypeCode { get; set; }
        public string TypeName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<MilitaryEquipment> MilitaryEquipment { get; set; }
    }
}
