//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilichevKurs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentStatus
    {
        public EquipmentStatus()
        {
            this.MilitaryEquipment = new HashSet<MilitaryEquipment>();
        }
    
        public int StatusID { get; set; }
        public string StatusName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<MilitaryEquipment> MilitaryEquipment { get; set; }
    }
}
