//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilichevKurs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventEquipment
    {
        public int EventEquipmentID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public string RoleInEvent { get; set; }
        public Nullable<bool> IsMainAttraction { get; set; }
    
        public virtual MilitaryEquipment MilitaryEquipment { get; set; }
        public virtual Events Events { get; set; }
    }
}
