//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilichevKurs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventParticipations
    {
        public int ParticipationID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<bool> Attended { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Events Events { get; set; }
    }
}
