//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilichevKurs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public Events()
        {
            this.EventEquipment = new HashSet<EventEquipment>();
            this.EventParticipations = new HashSet<EventParticipations>();
        }
    
        public int EventID { get; set; }
        public string EventName { get; set; }
        public Nullable<int> EventTypeID { get; set; }
        public System.DateTime EventDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public Nullable<int> MaxParticipants { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ResponsibleEmployeeID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual ICollection<EventEquipment> EventEquipment { get; set; }
        public virtual ICollection<EventParticipations> EventParticipations { get; set; }
        public virtual EventTypes EventTypes { get; set; }
    }
}
