//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilichevKurs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilitaryEquipment
    {
        public MilitaryEquipment()
        {
            this.EventEquipment = new HashSet<EventEquipment>();
        }
    
        public int EquipmentID { get; set; }
        public string InventoryNumber { get; set; }
        public string Name { get; set; }
        public int TypeID { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> ProductionYear { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<int> Crew { get; set; }
        public Nullable<int> MaxSpeed { get; set; }
        public Nullable<int> EnginePower { get; set; }
        public string ArmorType { get; set; }
        public string Armament { get; set; }
        public string Description { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> RestorationDate { get; set; }
    
        public virtual EquipmentStatus EquipmentStatus { get; set; }
        public virtual EquipmentTypes EquipmentTypes { get; set; }
        public virtual ICollection<EventEquipment> EventEquipment { get; set; }
        public object Photo { get; internal set; }
    }
}
