//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilichevKurs.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilichevKursEntities : DbContext
    {
        public FilichevKursEntities()
            : base("name=FilichevKursEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clients> Clients { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<EquipmentStatus> EquipmentStatus { get; set; }
        public DbSet<EquipmentTypes> EquipmentTypes { get; set; }
        public DbSet<EventEquipment> EventEquipment { get; set; }
        public DbSet<EventParticipations> EventParticipations { get; set; }
        public DbSet<Events> Events { get; set; }
        public DbSet<EventTypes> EventTypes { get; set; }
        public DbSet<MilitaryEquipment> MilitaryEquipment { get; set; }
        public DbSet<Positions> Positions { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
